#!/bin/bash

# Get new tarball and try to build nova
#


abspath="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
dirname="$(dirname $abspath)"
cd "$dirname" || exit -1

prj="nova"
DevMileStone="d4"
TarballsHome="http://nova.openstack.org/tarballs"

CurTarballVer=(`curl -s $TarballsHome/?C=M\;O=D| grep $DevMileStone | grep -m 1 $prj-[0-9] | perl -p -e 's!^.*$prj-(\d+\.\d+)~(\w\d)~(\d+.r*\d+)\.tar\.gz.*$!\n$1 $2 $3 $4 $5\n!i'`)
source trigger.conf
source build_helpers


# If you need to build a specific version - specify it as ./build release_num (digits only).
# If build # is not specified, latest available tarball will be built



get_tarball
create_srpm
create_rpm
sign_rpm
