#!/bin/bash

prj="swift"
source /var/lib/jenkins/jobs/nova-trunk/workspace/trigger.conf

CurTarballVer=(`curl -s $TarballsHome/?C=M\;O=D| grep -m 1 swift-[0-9] | perl -p -e 's!^.*swift-(\d+\.\d+\.\d+)~(\d+\.\d+)\.tar\.gz.*$!\n$1 $2 $3 $4 $5\n!i'`)

ActualVersion=${CurTarballVer[0]}
ActualRelease=$ReleasePreSymbol${CurTarballVer[1]}
ActualTarBall="$prj-$ActualVersion~${CurTarballVer[1]}.tar.gz"

source /var/lib/jenkins/jobs/nova-trunk/workspace/build_helpers


# If you need to build a specific version - specify it as ./build release_num (digits only).
# If build # is not specified, latest available tarball will be built



case "$1" in
    build)
        check_for_update
        check_enviroment
        update_spec

	get_tarball
	create_srpm
	create_rpm || undo_changes
	sign_rpm
	update_repo
	#do_mock
        ;;
    check)
	check_for_update 
	curl -s "http://$jenkins/job/$JobName/build"
	[ $Debug ] && echo "Fire jenkins to build $JobName"
	 exit 0
        ;;
    release)
	ActualRelease=$2
	build
	;;
    *)
        echo $"Usage: $0 {build|check|release}"
        echo "build - build rpms"
        echo "check - check for updates and trigger jenkins"
        echo "release NUM - build specified release"
        exit 2
esac
exit $?
